### ISSUE TITLE
concatenate multiple json keys to one result object property

### ISSUE THREAD

**Issue by VilemKurz** [lucasmedeirosleite/EasyMapping#129]
e.g. you have latitude and longitude keys in object's JSON. The object can have coordinate property. We need object mapping method with parameters  "keysArray" "toProperty" and valueBlock with dictionary parameter containing "keysArray keys and their values", so that we can create a single property (e.g. CGRect or CGSize or CLLocationCoordinate2D) from supplied values dictionary

And big thank you for this awesome mapping lib :)

**Comment by sebastianludwig** [comment]
I started looking into this as well. If you're lucky and all values are grouped together under a parent key, you can achieve this with the normal value mapping block. There's an example in the spec: `with custom object returned`.

**Comment by DenHeadless** [comment]
We don't have this feature right now, unfortunately. Seems like an overkill to implement it, since it requires us to rewrite property mapping handling code. However, if you have an idea of how to implement this feature without major changes - we can definitely discuss adding it to the project.

**Comment by sebastianludwig** [comment]
My approach was to add a new type of mapping `EKCompoundMapping`, similar to `EKRelationshipMapping`. I pushed my [work in progress](https://github.com/sebastianludwig/EasyMapping/tree/compound_properties) - it's just far enough to figure out I could do it with common parent approach described above ;-) Anyway, feel free to take a look and give some feedback, I might continue to work on this if I've got some more time on my hands.

**Comment by DenHeadless** [comment]
Actually, it seems like we have part of this feature, which i completely forgot about, since it's used so rarely. Can you look if that's what you're looking for?

There's a method to map several keypaths to single hasOne relationship
https://github.com/lucasmedeirosleite/EasyMapping/blob/master/EasyMapping/EKObjectMapping.h#L238-L241

Which then is unwrapped in the way similar to what you are proposing, here:

https://github.com/lucasmedeirosleite/EasyMapping/blob/master/EasyMapping/EKRelationshipMapping.m#L18-L37

**Comment by armandzwan** [comment]
Something like **Mapping Values without Key Paths** at 
[https://github.com/RestKit/RestKit/wiki/Object-mapping](url)

**Comment by DenTelezhkin** [comment]
This issue is stale, if you want to pursue this functionality with EasyMapping, pull request is greatly appreciated.

Closing issue for now.
