### ISSUE TITLE
Proper Swift support

### ISSUE THREAD

**Issue by gaydukov-nikita** [lucasmedeirosleite/EasyMapping#134]
Hi 

Are there any plans for a proper Swift support? I mean mapping to Swift objects: Int,Float etc.
Great library by the way!

Thanks.

**Comment by DenHeadless** [comment]
Yes and no. **Proper** support for Swift seems impossible, because Swift enforces filling out all variables in constructor, which EasyMapping just can't do, as it fills them afterwards using KVC.

However, partially EasyMapping works, since Swift Int, Float, Double and Bool are automatically bridged to Objective-C NSNumber.

Also, if you use CoreData, EasyMapping works great in Swift, since all properties are dynamic.

I'm planning to also add nullability annotations for next release, so all implicitly unwrapped optionals will be gone.

Hope that answers your question, feel free to reopen this issue if you have any other ideas concerning Swift support.
