### ISSUE TITLE
Keep track of order

### ISSUE THREAD

**Issue by armandzwan** [lucasmedeirosleite/EasyMapping#138]
I want to map a GeoJSON file to Core Data. Now I'm bumping into the problem that the coordinates do not have an "order" attribute in the json. How do I keep the order when saving to Core Data? Can it be done with "withValueBlock" ?

Or just checking the ordered checkbox at the "to Many" type?
Can I trust EasyMapping will add the coordinates in the same order as the json?

Example json part:
```
 "coordinates":
[ // multipolygons
[ // polygons
 [ // rings
   [ // coordinates
      6.8060, 
      54.1236
    ], 
    [
       6.806, 
       54.1236
    ], 
    [
       6.8060, 
       54.1236
    ]
 ]
]
]
```

**Comment by DenHeadless** [comment]
EasyMapping uses data type of your model to determine which data structure should be used. You can take a look at this method to get a better understanding of what's going on: https://github.com/lucasmedeirosleite/EasyMapping/blob/master/EasyMapping/EKPropertyHelper.m#L64

You need to also think about your CoreData representation of your values, because CoreData does not have Array data structure. You can have an ordered set at best, and if you have - EasyMapping will simply call NSOrderedSet.orderedSetWithArray method, which should keep your order as it is in JSON.

Hope this helps solving your task.

**Comment by armandzwan** [comment]
Thanks for the quick reply!

I have come all the way down to coordinates, by giving all the arrays a "key"
Like: 
`"MultiPolygons": [
                          {
          "Polygons" :
          [
           {
           "Rings":
            	[{
                 "Coordinates":`
etc
But then ...
How can I loop through all the coordinates in "Coordinates" : ?

`[mapping mapKeyPath:@"Coordinates" toProperty:@"hasCoordinates" withValueBlock:^id _Nullable(NSString * _Nonnull key, id  _Nullable value, NSManagedObjectContext * _Nonnull context) {`
Create an NSOrderedSet from all the objects in the id value (NSArray) and return that?

**Comment by DenHeadless** [comment]
Pretty much, yeah. I assume you have an entity for Coordinate, right? Coordinates usualy are stored as double values in CoreData, so you might have NSOrderedSet of Coordinate objects.

**Comment by armandzwan** [comment]
Thanks. I will give it a go!
