### ISSUE TITLE
Clean way to set default date formatter

### ISSUE THREAD

**Issue by sebastianludwig** [lucasmedeirosleite/EasyMapping#139]
Is there a cleaner way to set the date formatter used by default?

```
NSMutableDictionary *dictionary = [[NSThread currentThread] threadDictionary];
dictionary[@"EKThreadDateFormatter"] = mySpecialFormatter;
```

feels very dirty because it uses internal knowledge.

How about a setter in `NSDateFormatter+EasyMappingAdditions.h`? And maybe get rid of the `threadDictionary` stuff? I think it's not necessary anymore to support iOS 6, with iOS 10 around the corner ;-)

Would you accept a PR?

**Comment by DenHeadless** [comment]
This property is already deprecated in https://github.com/lucasmedeirosleite/EasyMapping/releases/tag/0.18.0
release, and will be removed with release for Xcode 8, since it drops support for iOS 7 anyway. I think as a framework we'll simply accept any date formatter that has been passed to us, and leave the responsibility to store date formatter to developer using EasyMapping.

**Comment by sebastianludwig** [comment]
Nice, I think it's the right move to get rid of the extension 👍 However, my initial request still stands :-) I've to map a _lot_ of timestamps and it's very inconvenient to not be able to use the array or dictionary mapping methods, but to have to use the `mapKeyPath:toProperty:withDateFormatter:` for every date property. How about a `defaultDateFormatter` property on `EKObjectMapping`, maybe even `EKMapper` (the the `Managed` counterparts)?

**Comment by DenHeadless** [comment]
How would you call this method then? Right now date mapping is a simple value block mapping, that uses date formatter that was passed to us.
Right now we don't have mapping types(**how** to map specific field to property), so we can't use array and dictionary mapping methods, since they don't have value block conversion for properties.

I'm not opposed to idea of having default date formatter as an additional feature, but not as a replacement for original method. If you have a good idea of where to put this property and how to use it, while still supporting original method - that would be nice to have.

**Comment by sebastianludwig** [comment]
Oh yeah, definitely! I never meant to replace the original method. I'll look into it and come back with a concrete proposal.
