### ISSUE TITLE
EasyMapping vs FastEasyMapping

### ISSUE THREAD

**Issue by jcavar** [lucasmedeirosleite/EasyMapping#153]
Hi,
I have more of general question about these two libraries. We evaluated them both recently and they look quite similar, even bugs we encountered were the same in both of them.  API is quite similar, performance measurements as well.

I am wondering if there is something in EasyMapping that is not available in FastEasyMapping or other way around? 
If not, would it make sense to merge them? That would simplify choice of mapping library and would probably make that one much better.

**Comment by jcavar** [comment]
I asked the same thing on FastEasyMapping:
https://github.com/Yalantis/FastEasyMapping/issues/84

**Comment by DenHeadless** [comment]
Hey!

Separation basically started with CoreData perfomance issue that was present in EasyMapping long time ago. It seems guys from Yalantis decided to make their own fork of the library, because along with perfomance improvements they wanted to make some functional and naming changes. 

Perfomance issue was resolved in EasyMapping in #47, #49 and #50. We introduced our own benchmark suite, against which we evaluate all changes that impact perfomance of CoreData import. 

Since then there were a lot of changes here and there in both libraries, i think one of the features missing in EasyMapping to this day is assignment policies, we never had time to implement those. I think guys from Yalantis can tell their side of story, maybe they have more features i'm not aware of, as well as some features maybe missing, but i'm not aware what exactly. One thing i'm pretty sure though, is that EasyMapping is not slow, despite `FastEasyMapping` existance.

I'm not sure that we would be able to merge, since a LOT of changes happen in both libraries, and it would be a nightmare to try align all those issues in both libraries.

I have a feeling that this issue should become part of Github stories(sorry, Instagram) and be pinned to this repository for everyone trying to find out the difference between two libraries =)

**Comment by dimazen** [comment]
I'll post my answer here :) 
Originally FEM was a fork of the EM but after I did transfer ownership of this repo to Yalantis - Github lost this "connection" between FEM and EM. 

Regarding performance as @DenHeadless already mentioned above EM has merged all of the FEM improvements regarding performance and now operates at the same speed as FEM. 
Why I've decided not to merge it back: mostly because of different "view" on how things should be developed further. At this point EM and FEM are quite different under the hood to be merged easily. 

From the features: hard to say exactly. Looks like EM offers more options to mappings while FEM design leads to easier extensibility (currently I'm finishing Realm support). Other than that they're pretty much the same.

**Comment by jcavar** [comment]
Thanks both. It seems that all of us agree that both libraries are very similar and have hard time finding differencies in functionality. 
And just look into recent example of 2 bugs we found. It is same bug in both libraries and we need to fix them in both places.

I don't know if any of you are willing to transition to another library. I know you both have user base and it is not great if they have to transition, but in our experience both libraries are fairly easy to integrate in project, so transitioning to another should be relatively straightforward.
We could provide some period of time where users could migrate and even provide steps or we can just accept bug fixes in one and do further development on another. I have no experience with this but there are good examples of how to do it I guess.

It is up to you to decide this, I just feel like both libraries and users would benefit of this.

In any case, thanks both for great work 🥇

**Comment by DenTelezhkin** [comment]
This is more of a historic issue, but I think it's time to close it, anyone who was interested, already got their answer ;) Thanks everyone.
