### ISSUE TITLE
primaryKey property unexplained

### ISSUE THREAD

**Issue by Apocryphon** [lucasmedeirosleite/EasyMapping#160]
How does the primaryKey property work? What happens when you set it to an attribute of an Managed Object? And what does primaryKeyPropertyMapping do exactly?

**Comment by armandzwan** [comment]
EasyMapping can find the object in the database by the primary key. Say if in the JSON there is a reference to an object with id 1, the primaryKey says what property to use to find it. Example:
``` + (EKManagedObjectMapping *)locationMapping {
return [EKManagedObjectMapping mappingForEntityName:NSStringFromClass([Location class]) withBlock:^(EKManagedObjectMapping *mapping)
  {
     mapping.primaryKey = @"location_id";
     [mapping mapPropertiesFromDictionary:@{@"LocationID" : @"location_id"}];
   }];
}
```

**Comment by DenHeadless** [comment]
Also primaryKey is used for data import. Usually, when you import data in database, you use Find-Or-Create pattern, however for large datasets finding n objects(essentially running n SQL queries) becomes very time-consuming. Which is why, according to Apple's recommendation, EasyMapping tries to analyze incoming JSON, and fetch all entities of single type in a single SQL query - using primaryKey, as it must be unique. 

You can see how it's done in [EKCoreDataImporter class](https://github.com/lucasmedeirosleite/EasyMapping/blob/master/Sources/EasyMapping/EKCoreDataImporter.m)


`primaryKeypropertyMapping` is used to get all property keys from JSON **before** objects are created, because we need to find all objects, that already exist in CoreData database before mapping process even starts.

**Comment by Apocryphon** [comment]
Thanks for the clarifications
